service: feelings-product-service

frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs14.x
  profile: ${file(./serverless-variables.json):profile}
  region: ${file(./serverless-variables.json):region}
  environment:
    PG_HOST: ${file(./serverless-variables.json):pg-host}
    PG_PORT: ${file(./serverless-variables.json):pg-port}
    PG_DATABASE: ${file(./serverless-variables.json):pg-database}
    PG_USERNAME: ${file(./serverless-variables.json):pg-username}
    PG_PASSWORD: ${file(./serverless-variables.json):pg-password}
  httpApi:
    cors:
      allowCredentials: true
      allowedOrigins:
        - ${self:custom.allowedOrigins.${opt:stage}}
      allowedMethods:
        - GET

plugins:
  - serverless-auto-swagger
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  domains:
    prod: cloud-x-training-api.${file(./serverless-variables.json):domain}
    dev: cloud-x-training-dev-api.${file(./serverless-variables.json):domain}
  allowedOrigins:
    prod: ${file(./serverless-variables.json):allowedOrigins-prod}
    dev: ${file(./serverless-variables.json):allowedOrigins-dev}
  autoswagger:
    basePath: '/product-service'
    host: ${self:custom.domains.${opt:stage}}
    schemes:
      - https
  customDomain:
    apiType: http
    endpointType: regional
    domainName: ${self:custom.domains.${opt:stage}}
    basePath: 'product-service'
    stage: ${opt:stage}
    createRoute53Record: true
    certificateName:  ${file(./serverless-variables.json):certificateName}
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true

functions:
  getProductsList:
    handler: src/functions/index.getProductsList
    events:
      - httpApi:
          path: /products
          method: GET

  getProductById:
    handler: src/functions/index.getProductById
    events:
      - httpApi:
          path: /products/{productId}
          method: GET
  createProduct:
    handler: src/functions/index.createProduct
    events:
      - httpApi:
          path: /products
          method: POST
